version: "3.4"

services:
  cozy-stack-couch:
    image: apache/couchdb:2.3
    ports:
      - 5984:5984
    volumes:
      - ./data/couchdb:/opt/couchdb/data

  cozy-stack:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 6060:6060
    image: cozy-stack
    volumes:
      - ./cozy-stack:/usr/local/bin/cozy-stack
      - ./data/cozy-stack:/go/storage
    depends_on:
      - cozy-stack-couch